import * as THREE from 'three';
import { getMaterial, UNIT_CHUNKY_BOX, UNIT_CYLINDER, UNIT_ROUNDED_BOX, UNIT_SPHERE } from '../world/Materials';
export interface NPC { root: THREE.Group; points: THREE.Vector3[]; progress:number; speed:number; paused:number; ambient?:boolean; crossing?:boolean; }
type Spec={p:[number,number,number][];s:number;b:any;h:any;k?:'hat'|'glasses'|'bag'|'backpack';a?:boolean;c?:boolean;z?:number};
const specs:Spec[]=[
{p:[[-6,.3,18],[6,.3,18],[6,.3,12],[-6,.3,12]],s:.82,b:'mint',h:'navy',k:'backpack'},{p:[[-5,.3,16],[5,.3,16],[5,.3,13],[-5,.3,13]],s:.7,b:'lavender',h:'brick',k:'glasses',z:.9},{p:[[-2,.3,20],[8,.3,20],[8,.3,17],[-2,.3,17]],s:.92,b:'coral',h:'terracotta',k:'hat',z:1.08},{p:[[1,.3,14],[-8,.3,14],[-8,.3,11],[1,.3,11]],s:.64,b:'butter',h:'dustyRose',k:'bag',z:.84},
{p:[[-25,.3,-7],[-12,.3,-7],[-12,.3,7],[-25,.3,7]],s:.7,b:'turquoise',h:'navy',k:'bag'},{p:[[-23,.3,6],[-14,.3,6],[-14,.3,-5],[-23,.3,-5]],s:.86,b:'coral',h:'brick',k:'hat',z:.93},{p:[[-20,.3,-2],[-16,.3,-2]],s:.5,b:'lavender',h:'terracotta',k:'backpack',a:true,z:1.1},{p:[[-18,.3,2],[-14,.3,2]],s:.45,b:'mint',h:'dustyRose',k:'bag',a:true,z:.78},
{p:[[12,.3,-6],[25,.3,-6],[25,.3,6],[12,.3,6]],s:.62,b:'butter',h:'navy',k:'glasses',z:.95},{p:[[15,.3,5],[23,.3,5],[23,.3,1],[15,.3,1]],s:.5,b:'turquoise',h:'brick',a:true,z:1.05},{p:[[19,.3,-1],[22,.3,-1]],s:.4,b:'coral',h:'terracotta',k:'hat',a:true,z:.82},{p:[[-30,.3,20],[-30,.3,-20]],s:.76,b:'mint',h:'navy',k:'backpack'},{p:[[-29,.3,-16],[-29,.3,16]],s:.58,b:'lavender',h:'dustyRose',k:'bag',z:.9},{p:[[0,.3,3],[0,.3,-3]],s:.42,b:'butter',h:'brick',k:'glasses',c:true,z:.86},{p:[[-3,.3,27],[-1,.3,27]],s:.25,b:'turquoise',h:'terracotta',a:true,z:1.05},{p:[[-8,.3,-29],[-5,.3,-29]],s:.22,b:'coral',h:'navy',k:'bag',a:true,z:.8}];
export class NPCSystem { readonly root=new THREE.Group(); private readonly npcs:NPC[]=[]; private elapsed=0; readonly activeCount=specs.filter(s=>!s.a).length; readonly ambientCount=specs.filter(s=>s.a).length;
 constructor(){this.root.name='Pedestrians';specs.forEach((s,i)=>this.add(s,i));}
 private add(s:Spec,i:number){const g=new THREE.Group(),q=s.z??1, body=new THREE.Mesh(UNIT_ROUNDED_BOX,getMaterial(s.b)),head=new THREE.Mesh(UNIT_SPHERE,getMaterial('peach')),hair=new THREE.Mesh(UNIT_SPHERE,getMaterial(s.h)); body.scale.set(.23*q,.52*q,.2*q);body.position.y=.48*q;head.scale.set(.27*q,.29*q,.27*q);head.position.y=1.12*q;hair.scale.set(.23*q,.12*q,.23*q);hair.position.y=1.34*q;g.add(body,head,hair);if(s.k==='hat'){const m=new THREE.Mesh(UNIT_CYLINDER,getMaterial('cream'));m.scale.set(.28*q,.12*q,.28*q);m.position.y=1.48*q;g.add(m);}if(s.k==='glasses'){const m=new THREE.Mesh(UNIT_CHUNKY_BOX,getMaterial('navy'));m.scale.set(.18*q,.035,.035);m.position.set(0,1.14*q,.25*q);g.add(m);}if(s.k==='bag'||s.k==='backpack'){const m=new THREE.Mesh(UNIT_CHUNKY_BOX,getMaterial(s.k==='bag'?'butter':'lavender'));m.scale.set(.14*q,.2*q,.1*q);m.position.set(s.k==='bag'?.28:-.28,.55*q,0);g.add(m);}g.position.set(...s.p[0]!);this.root.add(g);this.npcs.push({root:g,points:s.p.map(p=>new THREE.Vector3(...p)),progress:i*.37,speed:s.s,paused:s.a?.35:0,ambient:s.a,crossing:s.c});}
 update(dt:number,playerPosition:THREE.Vector3,cake:any){this.elapsed+=dt;for(const n of this.npcs){if(n.paused>0){n.paused-=dt;n.root.rotation.y=Math.sin(this.elapsed*1.5+n.progress)*.08;continue;}const a=n.points[Math.floor(n.progress)%n.points.length]!,b=n.points[(Math.floor(n.progress)+1)%n.points.length]!;n.root.position.lerpVectors(a,b,n.progress%1);n.progress+=dt*n.speed/Math.max(.1,a.distanceTo(b));n.root.lookAt(b.x,n.root.position.y,b.z);if(n.root.position.distanceTo(playerPosition)<.7){n.paused=n.crossing?.7:.35;if(cake)cake.impact(.8);}}}
 reset(){this.elapsed=0;this.npcs.forEach(n=>{n.progress=0;n.paused=n.ambient?.35:0;n.root.position.copy(n.points[0]!);});}
}
