import * as THREE from 'three';import type { CakePackage } from '../delivery/CakePackage';import { getMaterial,UNIT_CHUNKY_BOX,UNIT_CYLINDER,UNIT_ROUNDED_BOX,UNIT_SPHERE } from '../world/Materials';import type { WorldEventDefinition,WorldEventMapMetadata } from './WorldEventTypes';
export class WorldEvent {readonly root=new THREE.Group();private elapsed=0;private hitCooldown=0;private initial=new THREE.Vector3();
 constructor(readonly definition:WorldEventDefinition){this.root.name=`WorldEvent:${definition.id}`;this.root.position.set(...definition.position);this.initial.copy(this.root.position);this.build();}
 get mapMetadata():WorldEventMapMetadata{const d=this.definition;return{id:d.id,name:d.name,description:d.description,icon:d.icon,affectedRoute:d.affectedRoute,mapLabel:d.mapLabel,routeStatus:d.routeStatus,challengeLabel:d.challengeLabel,bonus:d.bonus};}
 private mesh(color:any,scale:[number,number,number],position:[number,number,number],rounded=false){const m=new THREE.Mesh(rounded?UNIT_ROUNDED_BOX:UNIT_CHUNKY_BOX,getMaterial(color));m.scale.set(...scale);m.position.set(...position);m.castShadow=true;return m;}
 private build(){const k=this.definition.kind;if(k==='barriers'){for(const x of [-1.7,1.7]){this.root.add(this.mesh('coral',[1.1,.5,.18],[x,.45,0]));for(const dx of [-.65,0,.65]){const cone=new THREE.Mesh(UNIT_CYLINDER,getMaterial('warmOrange'));cone.scale.set(.13,.32,.13);cone.position.set(x+dx,.22,.55);this.root.add(cone);}}}else if(k==='crowd'){for(let i=0;i<6;i++){const p=new THREE.Group(),body=new THREE.Mesh(UNIT_ROUNDED_BOX,getMaterial(i%2?'lavender':'mint')),head=new THREE.Mesh(UNIT_SPHERE,getMaterial('peach'));body.scale.set(.22,.45,.2);body.position.y=.5;head.scale.setScalar(.25);head.position.y=1.1;p.add(body,head);p.position.set((i%3-1)*1.1,0,(Math.floor(i/3)-.5)*1.3);this.root.add(p);}}else if(k==='van'){this.root.add(this.mesh('turquoise',[1.7,.65,.85],[0,.65,0],true),this.mesh('cream',[.8,.45,.75],[-.25,1.15,0]),this.mesh('coral',[.12,.72,.78],[1.72,.75,0]));}else if(k==='sprinklers'){for(const z of [-2,2]){const base=new THREE.Mesh(UNIT_CYLINDER,getMaterial('navy'));base.scale.set(.22,.18,.22);base.position.set(0,.18,z);const water=new THREE.Mesh(UNIT_CYLINDER,getMaterial('powderBlue',{transparent:true,opacity:.55}));water.scale.set(.07,2.2,.07);water.rotation.z=Math.PI/2;water.position.set(1.8,.75,z);water.name='water';this.root.add(base,water);}}else{this.root.add(this.mesh('dustyRose',[1.7,.65,.5],[0,1,0],true));for(const x of [-2,2]){const mover=new THREE.Group(),body=new THREE.Mesh(UNIT_ROUNDED_BOX,getMaterial('butter')),head=new THREE.Mesh(UNIT_SPHERE,getMaterial('peach'));body.scale.set(.22,.45,.2);body.position.y=.5;head.scale.setScalar(.24);head.position.y=1.08;mover.add(body,head);mover.position.x=x;this.root.add(mover);}}}
 update(dt:number,player:THREE.Vector3,cake:CakePackage|null){this.elapsed+=dt;this.hitCooldown=Math.max(0,this.hitCooldown-dt);const k=this.definition.kind;if(k==='crowd')this.root.children.forEach((c,i)=>c.position.z+=Math.sin(this.elapsed*1.4+i)*dt*.25);if(k==='van')this.root.position.x=this.initial.x+Math.sin(this.elapsed*.45)*1.4;if(k==='furniture')this.root.position.z=this.initial.z+Math.sin(this.elapsed*.7)*4;if(k==='sprinklers'){const active=this.elapsed%6>1.5&&this.elapsed%6<4.5;this.root.children.filter(c=>c.name==='water').forEach(c=>{c.visible=active;c.rotation.y=this.elapsed*2;});if(active&&this.root.position.distanceTo(player)<4&&cake)cake.addExternalStress(1.35);}const localX=player.x-this.root.position.x,localZ=player.z-this.root.position.z,barrierHit=k==='barriers'&&Math.abs(localZ)<.8&&(Math.abs(localX-1.7)<1.1||Math.abs(localX+1.7)<1.1),crowdHit=k==='crowd'&&this.root.children.some(c=>Math.hypot(localX-c.position.x,localZ-c.position.z)<.7),solidHit=(k==='van'||k==='furniture')&&this.root.position.distanceTo(player)<2;if((barrierHit||crowdHit||solidHit)&&cake&&this.hitCooldown===0){cake.impact(k==='van'?12:k==='furniture'?8:k==='barriers'?5:.8);this.hitCooldown=.6;}}
 reset(){this.elapsed=0;this.hitCooldown=0;this.root.position.copy(this.initial);}dispose(){this.root.removeFromParent();}
}
